/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadgeRibbon: typeof import('ant-design-vue/es')['BadgeRibbon']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AImage: typeof import('ant-design-vue/es')['Image']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    AQrcode: typeof import('ant-design-vue/es')['QRCode']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
